services:
  web:
    container_name: web
    build:
      context: .
    command: sh /app/entrypoints.sh
    ports:
      - "7000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - back_media:/app/media
      - back_static:/app/static
    depends_on:
      - db
      - redis

  db:
    container_name: db
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7
    volumes:
      - redis-data:/data

  celery_worker:
    container_name: celery_worker
    build:
      context: .
    command: celery -A shop_api worker --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  celery_beat:
    container_name: celery_beat
    build:
      context: .
    command: celery -A shop_api beat --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  celery_flower:
    container_name: celery_flower
    build:
      context: .
    command: celery -A shop_api flower --port=5555
    ports:
      - "5555:5555"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis

  nginx:
    container_name: nginx
    image: nginx:1.25
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - back_media:/app/media
      - back_static:/app/static

volumes:
  db-data:
  redis-data:
  back_media:
  back_static: